//
// Created by Austin Clyde on 8/2/21.
//

#include <stdlib.h>
#include <stdio.h>

#include "scoring.h"

int edit_distance_scoring(char a, char b) {
    if (a == b) {
        return 1;
    } else {
        return -1;
    }
}

int blosum62_protein_scoring(char a, char b) {
    switch (a) {
        case 'A':
        case 'a':
            switch (b) {
                case 'A':
                case 'a':
                    return 4;
                case 'R':
                case 'r':
                    return -1;
                case 'N':
                case 'n':
                    return -2;
                case 'D':
                case 'd':
                    return -2;
                case 'C':
                case 'c':
                    return 0;
                case 'Q':
                case 'q':
                    return -1;
                case 'E':
                case 'e':
                    return -1;
                case 'G':
                case 'g':
                    return 0;
                case 'H':
                case 'h':
                    return -2;
                case 'I':
                case 'i':
                    return -1;
                case 'L':
                case 'l':
                    return -1;
                case 'K':
                case 'k':
                    return -1;
                case 'M':
                case 'm':
                    return -1;
                case 'F':
                case 'f':
                    return -2;
                case 'P':
                case 'p':
                    return -1;
                case 'S':
                case 's':
                    return 1;
                case 'T':
                case 't':
                    return 0;
                case 'W':
                case 'w':
                    return -3;
                case 'Y':
                case 'y':
                    return -2;
                case 'V':
                case 'v':
                    return 0;
                case 'B':
                case 'b':
                    return -2;
                case 'Z':
                case 'z':
                    return -1;
                case 'X':
                case 'x':
                    return 0;
                default:
                    printf("Error in Scoring. Not found (%c,%c)", a, b);
                    return 0;
            }
            break;
        case 'R':
        case 'r':
            switch (b) {
                case 'A':
                case 'a':
                    return -1;
                case 'R':
                case 'r':
                    return 5;
                case 'N':
                case 'n':
                    return 0;
                case 'D':
                case 'd':
                    return -2;
                case 'C':
                case 'c':
                    return -3;
                case 'Q':
                case 'q':
                    return 1;
                case 'E':
                case 'e':
                    return 0;
                case 'G':
                case 'g':
                    return -2;
                case 'H':
                case 'h':
                    return 0;
                case 'I':
                case 'i':
                    return -3;
                case 'L':
                case 'l':
                    return -2;
                case 'K':
                case 'k':
                    return 2;
                case 'M':
                case 'm':
                    return -1;
                case 'F':
                case 'f':
                    return -3;
                case 'P':
                case 'p':
                    return -2;
                case 'S':
                case 's':
                    return -1;
                case 'T':
                case 't':
                    return -1;
                case 'W':
                case 'w':
                    return -3;
                case 'Y':
                case 'y':
                    return -2;
                case 'V':
                case 'v':
                    return -3;
                case 'B':
                case 'b':
                    return -1;
                case 'Z':
                case 'z':
                    return 0;
                case 'X':
                case 'x':
                    return -1;
                default:
                    printf("Error in Scoring. Not found (%c,%c)", a, b);
                    return 0;
            }
            break;
        case 'N':
        case 'n':
            switch (b) {
                case 'A':
                case 'a':
                    return -2;
                case 'R':
                case 'r':
                    return 0;
                case 'N':
                case 'n':
                    return 6;
                case 'D':
                case 'd':
                    return 1;
                case 'C':
                case 'c':
                    return -3;
                case 'Q':
                case 'q':
                    return 0;
                case 'E':
                case 'e':
                    return 0;
                case 'G':
                case 'g':
                    return 0;
                case 'H':
                case 'h':
                    return 1;
                case 'I':
                case 'i':
                    return -3;
                case 'L':
                case 'l':
                    return -3;
                case 'K':
                case 'k':
                    return 0;
                case 'M':
                case 'm':
                    return -2;
                case 'F':
                case 'f':
                    return -3;
                case 'P':
                case 'p':
                    return -2;
                case 'S':
                case 's':
                    return 1;
                case 'T':
                case 't':
                    return 0;
                case 'W':
                case 'w':
                    return -4;
                case 'Y':
                case 'y':
                    return -2;
                case 'V':
                case 'v':
                    return -3;
                case 'B':
                case 'b':
                    return 3;
                case 'Z':
                case 'z':
                    return 0;
                case 'X':
                case 'x':
                    return -1;
                default:
                    printf("Error in Scoring. Not found (%c,%c)", a, b);
                    return 0;
            }
            break;
        case 'D':
        case 'd':
            switch (b) {
                case 'A':
                case 'a':
                    return -2;
                case 'R':
                case 'r':
                    return -2;
                case 'N':
                case 'n':
                    return 1;
                case 'D':
                case 'd':
                    return 6;
                case 'C':
                case 'c':
                    return -3;
                case 'Q':
                case 'q':
                    return 0;
                case 'E':
                case 'e':
                    return 2;
                case 'G':
                case 'g':
                    return -1;
                case 'H':
                case 'h':
                    return -1;
                case 'I':
                case 'i':
                    return -3;
                case 'L':
                case 'l':
                    return -4;
                case 'K':
                case 'k':
                    return -1;
                case 'M':
                case 'm':
                    return -3;
                case 'F':
                case 'f':
                    return -3;
                case 'P':
                case 'p':
                    return -1;
                case 'S':
                case 's':
                    return 0;
                case 'T':
                case 't':
                    return -1;
                case 'W':
                case 'w':
                    return -4;
                case 'Y':
                case 'y':
                    return -3;
                case 'V':
                case 'v':
                    return -3;
                case 'B':
                case 'b':
                    return 4;
                case 'Z':
                case 'z':
                    return 1;
                case 'X':
                case 'x':
                    return -1;
                default:
                    printf("Error in Scoring. Not found (%c,%c)", a, b);
                    return 0;
            }
            break;
        case 'C':
        case 'c':
            switch (b) {
                case 'A':
                case 'a':
                    return 0;
                case 'R':
                case 'r':
                    return -3;
                case 'N':
                case 'n':
                    return -3;
                case 'D':
                case 'd':
                    return -3;
                case 'C':
                case 'c':
                    return 9;
                case 'Q':
                case 'q':
                    return -3;
                case 'E':
                case 'e':
                    return -4;
                case 'G':
                case 'g':
                    return -3;
                case 'H':
                case 'h':
                    return -3;
                case 'I':
                case 'i':
                    return -1;
                case 'L':
                case 'l':
                    return -1;
                case 'K':
                case 'k':
                    return -3;
                case 'M':
                case 'm':
                    return -1;
                case 'F':
                case 'f':
                    return -2;
                case 'P':
                case 'p':
                    return -3;
                case 'S':
                case 's':
                    return -1;
                case 'T':
                case 't':
                    return -1;
                case 'W':
                case 'w':
                    return -2;
                case 'Y':
                case 'y':
                    return -2;
                case 'V':
                case 'v':
                    return -1;
                case 'B':
                case 'b':
                    return -3;
                case 'Z':
                case 'z':
                    return -3;
                case 'X':
                case 'x':
                    return -2;
                default:
                    printf("Error in Scoring. Not found (%c,%c)", a, b);
                    return 0;
            }
            break;
        case 'Q':
        case 'q':
            switch (b) {
                case 'A':
                case 'a':
                    return -1;
                case 'R':
                case 'r':
                    return 1;
                case 'N':
                case 'n':
                    return 0;
                case 'D':
                case 'd':
                    return 0;
                case 'C':
                case 'c':
                    return -3;
                case 'Q':
                case 'q':
                    return 5;
                case 'E':
                case 'e':
                    return 2;
                case 'G':
                case 'g':
                    return -2;
                case 'H':
                case 'h':
                    return 0;
                case 'I':
                case 'i':
                    return -3;
                case 'L':
                case 'l':
                    return -2;
                case 'K':
                case 'k':
                    return 1;
                case 'M':
                case 'm':
                    return 0;
                case 'F':
                case 'f':
                    return -3;
                case 'P':
                case 'p':
                    return -1;
                case 'S':
                case 's':
                    return 0;
                case 'T':
                case 't':
                    return -1;
                case 'W':
                case 'w':
                    return -2;
                case 'Y':
                case 'y':
                    return -1;
                case 'V':
                case 'v':
                    return -2;
                case 'B':
                case 'b':
                    return 0;
                case 'Z':
                case 'z':
                    return 3;
                case 'X':
                case 'x':
                    return -1;
                default:
                    printf("Error in Scoring. Not found (%c,%c)", a, b);
                    return 0;
            }
            break;
        case 'E':
        case 'e':
            switch (b) {
                case 'A':
                case 'a':
                    return -1;
                case 'R':
                case 'r':
                    return 0;
                case 'N':
                case 'n':
                    return 0;
                case 'D':
                case 'd':
                    return 2;
                case 'C':
                case 'c':
                    return -4;
                case 'Q':
                case 'q':
                    return 2;
                case 'E':
                case 'e':
                    return 5;
                case 'G':
                case 'g':
                    return -2;
                case 'H':
                case 'h':
                    return 0;
                case 'I':
                case 'i':
                    return -3;
                case 'L':
                case 'l':
                    return -3;
                case 'K':
                case 'k':
                    return 1;
                case 'M':
                case 'm':
                    return -2;
                case 'F':
                case 'f':
                    return -3;
                case 'P':
                case 'p':
                    return -1;
                case 'S':
                case 's':
                    return 0;
                case 'T':
                case 't':
                    return -1;
                case 'W':
                case 'w':
                    return -3;
                case 'Y':
                case 'y':
                    return -2;
                case 'V':
                case 'v':
                    return -2;
                case 'B':
                case 'b':
                    return 1;
                case 'Z':
                case 'z':
                    return 4;
                case 'X':
                case 'x':
                    return -1;
                default:
                    printf("Error in Scoring. Not found (%c,%c)", a, b);
                    return 0;
            }
            break;
        case 'G':
        case 'g':
            switch (b) {
                case 'A':
                case 'a':
                    return 0;
                case 'R':
                case 'r':
                    return -2;
                case 'N':
                case 'n':
                    return 0;
                case 'D':
                case 'd':
                    return -1;
                case 'C':
                case 'c':
                    return -3;
                case 'Q':
                case 'q':
                    return -2;
                case 'E':
                case 'e':
                    return -2;
                case 'G':
                case 'g':
                    return 6;
                case 'H':
                case 'h':
                    return -2;
                case 'I':
                case 'i':
                    return -4;
                case 'L':
                case 'l':
                    return -4;
                case 'K':
                case 'k':
                    return -2;
                case 'M':
                case 'm':
                    return -3;
                case 'F':
                case 'f':
                    return -3;
                case 'P':
                case 'p':
                    return -2;
                case 'S':
                case 's':
                    return 0;
                case 'T':
                case 't':
                    return -2;
                case 'W':
                case 'w':
                    return -2;
                case 'Y':
                case 'y':
                    return -3;
                case 'V':
                case 'v':
                    return -3;
                case 'B':
                case 'b':
                    return -1;
                case 'Z':
                case 'z':
                    return -2;
                case 'X':
                case 'x':
                    return -1;
                default:
                    printf("Error in Scoring. Not found (%c,%c)", a, b);
                    return 0;
            }
            break;
        case 'H':
        case 'h':
            switch (b) {
                case 'A':
                case 'a':
                    return -2;
                case 'R':
                case 'r':
                    return 0;
                case 'N':
                case 'n':
                    return 1;
                case 'D':
                case 'd':
                    return -1;
                case 'C':
                case 'c':
                    return -3;
                case 'Q':
                case 'q':
                    return 0;
                case 'E':
                case 'e':
                    return 0;
                case 'G':
                case 'g':
                    return -2;
                case 'H':
                case 'h':
                    return 8;
                case 'I':
                case 'i':
                    return -3;
                case 'L':
                case 'l':
                    return -3;
                case 'K':
                case 'k':
                    return -1;
                case 'M':
                case 'm':
                    return -2;
                case 'F':
                case 'f':
                    return -1;
                case 'P':
                case 'p':
                    return -2;
                case 'S':
                case 's':
                    return -1;
                case 'T':
                case 't':
                    return -2;
                case 'W':
                case 'w':
                    return -2;
                case 'Y':
                case 'y':
                    return 2;
                case 'V':
                case 'v':
                    return -3;
                case 'B':
                case 'b':
                    return 0;
                case 'Z':
                case 'z':
                    return 0;
                case 'X':
                case 'x':
                    return -1;
                default:
                    printf("Error in Scoring. Not found (%c,%c)", a, b);
                    return 0;
            }
            break;
        case 'I':
        case 'i':
            switch (b) {
                case 'A':
                case 'a':
                    return -1;
                case 'R':
                case 'r':
                    return -3;
                case 'N':
                case 'n':
                    return -3;
                case 'D':
                case 'd':
                    return -3;
                case 'C':
                case 'c':
                    return -1;
                case 'Q':
                case 'q':
                    return -3;
                case 'E':
                case 'e':
                    return -3;
                case 'G':
                case 'g':
                    return -4;
                case 'H':
                case 'h':
                    return -3;
                case 'I':
                case 'i':
                    return 4;
                case 'L':
                case 'l':
                    return 2;
                case 'K':
                case 'k':
                    return -3;
                case 'M':
                case 'm':
                    return 1;
                case 'F':
                case 'f':
                    return 0;
                case 'P':
                case 'p':
                    return -3;
                case 'S':
                case 's':
                    return -2;
                case 'T':
                case 't':
                    return -1;
                case 'W':
                case 'w':
                    return -3;
                case 'Y':
                case 'y':
                    return -1;
                case 'V':
                case 'v':
                    return 3;
                case 'B':
                case 'b':
                    return -3;
                case 'Z':
                case 'z':
                    return -3;
                case 'X':
                case 'x':
                    return -1;
                default:
                    printf("Error in Scoring. Not found (%c,%c)", a, b);
                    return 0;
            }
            break;
        case 'L':
        case 'l':
            switch (b) {
                case 'A':
                case 'a':
                    return -1;
                case 'R':
                case 'r':
                    return -2;
                case 'N':
                case 'n':
                    return -3;
                case 'D':
                case 'd':
                    return -4;
                case 'C':
                case 'c':
                    return -1;
                case 'Q':
                case 'q':
                    return -2;
                case 'E':
                case 'e':
                    return -3;
                case 'G':
                case 'g':
                    return -4;
                case 'H':
                case 'h':
                    return -3;
                case 'I':
                case 'i':
                    return 2;
                case 'L':
                case 'l':
                    return 4;
                case 'K':
                case 'k':
                    return -2;
                case 'M':
                case 'm':
                    return 2;
                case 'F':
                case 'f':
                    return 0;
                case 'P':
                case 'p':
                    return -3;
                case 'S':
                case 's':
                    return -2;
                case 'T':
                case 't':
                    return -1;
                case 'W':
                case 'w':
                    return -2;
                case 'Y':
                case 'y':
                    return -1;
                case 'V':
                case 'v':
                    return 1;
                case 'B':
                case 'b':
                    return -4;
                case 'Z':
                case 'z':
                    return -3;
                case 'X':
                case 'x':
                    return -1;
                default:
                    printf("Error in Scoring. Not found (%c,%c)", a, b);
                    return 0;
            }
            break;
        case 'K':
        case 'k':
            switch (b) {
                case 'A':
                case 'a':
                    return -1;
                case 'R':
                case 'r':
                    return 2;
                case 'N':
                case 'n':
                    return 0;
                case 'D':
                case 'd':
                    return -1;
                case 'C':
                case 'c':
                    return -3;
                case 'Q':
                case 'q':
                    return 1;
                case 'E':
                case 'e':
                    return 1;
                case 'G':
                case 'g':
                    return -2;
                case 'H':
                case 'h':
                    return -1;
                case 'I':
                case 'i':
                    return -3;
                case 'L':
                case 'l':
                    return -2;
                case 'K':
                case 'k':
                    return 5;
                case 'M':
                case 'm':
                    return -1;
                case 'F':
                case 'f':
                    return -3;
                case 'P':
                case 'p':
                    return -1;
                case 'S':
                case 's':
                    return 0;
                case 'T':
                case 't':
                    return -1;
                case 'W':
                case 'w':
                    return -3;
                case 'Y':
                case 'y':
                    return -2;
                case 'V':
                case 'v':
                    return -2;
                case 'B':
                case 'b':
                    return 0;
                case 'Z':
                case 'z':
                    return 1;
                case 'X':
                case 'x':
                    return -1;
                default:
                    printf("Error in Scoring. Not found (%c,%c)", a, b);
                    return 0;
            }
            break;
        case 'M':
        case 'm':
            switch (b) {
                case 'A':
                case 'a':
                    return -1;
                case 'R':
                case 'r':
                    return -1;
                case 'N':
                case 'n':
                    return -2;
                case 'D':
                case 'd':
                    return -3;
                case 'C':
                case 'c':
                    return -1;
                case 'Q':
                case 'q':
                    return 0;
                case 'E':
                case 'e':
                    return -2;
                case 'G':
                case 'g':
                    return -3;
                case 'H':
                case 'h':
                    return -2;
                case 'I':
                case 'i':
                    return 1;
                case 'L':
                case 'l':
                    return 2;
                case 'K':
                case 'k':
                    return -1;
                case 'M':
                case 'm':
                    return 5;
                case 'F':
                case 'f':
                    return 0;
                case 'P':
                case 'p':
                    return -2;
                case 'S':
                case 's':
                    return -1;
                case 'T':
                case 't':
                    return -1;
                case 'W':
                case 'w':
                    return -1;
                case 'Y':
                case 'y':
                    return -1;
                case 'V':
                case 'v':
                    return 1;
                case 'B':
                case 'b':
                    return -3;
                case 'Z':
                case 'z':
                    return -1;
                case 'X':
                case 'x':
                    return -1;
                default:
                    printf("Error in Scoring. Not found (%c,%c)", a, b);
                    return 0;
            }
            break;
        case 'F':
        case 'f':
            switch (b) {
                case 'A':
                case 'a':
                    return -2;
                case 'R':
                case 'r':
                    return -3;
                case 'N':
                case 'n':
                    return -3;
                case 'D':
                case 'd':
                    return -3;
                case 'C':
                case 'c':
                    return -2;
                case 'Q':
                case 'q':
                    return -3;
                case 'E':
                case 'e':
                    return -3;
                case 'G':
                case 'g':
                    return -3;
                case 'H':
                case 'h':
                    return -1;
                case 'I':
                case 'i':
                    return 0;
                case 'L':
                case 'l':
                    return 0;
                case 'K':
                case 'k':
                    return -3;
                case 'M':
                case 'm':
                    return 0;
                case 'F':
                case 'f':
                    return 6;
                case 'P':
                case 'p':
                    return -4;
                case 'S':
                case 's':
                    return -2;
                case 'T':
                case 't':
                    return -2;
                case 'W':
                case 'w':
                    return 1;
                case 'Y':
                case 'y':
                    return 3;
                case 'V':
                case 'v':
                    return -1;
                case 'B':
                case 'b':
                    return -3;
                case 'Z':
                case 'z':
                    return -3;
                case 'X':
                case 'x':
                    return -1;
                default:
                    printf("Error in Scoring. Not found (%c,%c)", a, b);
                    return 0;
            }
            break;
        case 'P':
        case 'p':
            switch (b) {
                case 'A':
                case 'a':
                    return -1;
                case 'R':
                case 'r':
                    return -2;
                case 'N':
                case 'n':
                    return -2;
                case 'D':
                case 'd':
                    return -1;
                case 'C':
                case 'c':
                    return -3;
                case 'Q':
                case 'q':
                    return -1;
                case 'E':
                case 'e':
                    return -1;
                case 'G':
                case 'g':
                    return -2;
                case 'H':
                case 'h':
                    return -2;
                case 'I':
                case 'i':
                    return -3;
                case 'L':
                case 'l':
                    return -3;
                case 'K':
                case 'k':
                    return -1;
                case 'M':
                case 'm':
                    return -2;
                case 'F':
                case 'f':
                    return -4;
                case 'P':
                case 'p':
                    return 7;
                case 'S':
                case 's':
                    return -1;
                case 'T':
                case 't':
                    return -1;
                case 'W':
                case 'w':
                    return -4;
                case 'Y':
                case 'y':
                    return -3;
                case 'V':
                case 'v':
                    return -2;
                case 'B':
                case 'b':
                    return -2;
                case 'Z':
                case 'z':
                    return -1;
                case 'X':
                case 'x':
                    return -2;
                default:
                    printf("Error in Scoring. Not found (%c,%c)", a, b);
                    return 0;
            }
            break;
        case 'S':
        case 's':
            switch (b) {
                case 'A':
                case 'a':
                    return 1;
                case 'R':
                case 'r':
                    return -1;
                case 'N':
                case 'n':
                    return 1;
                case 'D':
                case 'd':
                    return 0;
                case 'C':
                case 'c':
                    return -1;
                case 'Q':
                case 'q':
                    return 0;
                case 'E':
                case 'e':
                    return 0;
                case 'G':
                case 'g':
                    return 0;
                case 'H':
                case 'h':
                    return -1;
                case 'I':
                case 'i':
                    return -2;
                case 'L':
                case 'l':
                    return -2;
                case 'K':
                case 'k':
                    return 0;
                case 'M':
                case 'm':
                    return -1;
                case 'F':
                case 'f':
                    return -2;
                case 'P':
                case 'p':
                    return -1;
                case 'S':
                case 's':
                    return 4;
                case 'T':
                case 't':
                    return 1;
                case 'W':
                case 'w':
                    return -3;
                case 'Y':
                case 'y':
                    return -2;
                case 'V':
                case 'v':
                    return -2;
                case 'B':
                case 'b':
                    return 0;
                case 'Z':
                case 'z':
                    return 0;
                case 'X':
                case 'x':
                    return 0;
                default:
                    printf("Error in Scoring. Not found (%c,%c)", a, b);
                    return 0;
            }
            break;
        case 'T':
        case 't':
            switch (b) {
                case 'A':
                case 'a':
                    return 0;
                case 'R':
                case 'r':
                    return -1;
                case 'N':
                case 'n':
                    return 0;
                case 'D':
                case 'd':
                    return -1;
                case 'C':
                case 'c':
                    return -1;
                case 'Q':
                case 'q':
                    return -1;
                case 'E':
                case 'e':
                    return -1;
                case 'G':
                case 'g':
                    return -2;
                case 'H':
                case 'h':
                    return -2;
                case 'I':
                case 'i':
                    return -1;
                case 'L':
                case 'l':
                    return -1;
                case 'K':
                case 'k':
                    return -1;
                case 'M':
                case 'm':
                    return -1;
                case 'F':
                case 'f':
                    return -2;
                case 'P':
                case 'p':
                    return -1;
                case 'S':
                case 's':
                    return 1;
                case 'T':
                case 't':
                    return 5;
                case 'W':
                case 'w':
                    return -2;
                case 'Y':
                case 'y':
                    return -2;
                case 'V':
                case 'v':
                    return 0;
                case 'B':
                case 'b':
                    return -1;
                case 'Z':
                case 'z':
                    return -1;
                case 'X':
                case 'x':
                    return 0;
                default:
                    printf("Error in Scoring. Not found (%c,%c)", a, b);
                    return 0;
            }
            break;
        case 'W':
        case 'w':
            switch (b) {
                case 'A':
                case 'a':
                    return -3;
                case 'R':
                case 'r':
                    return -3;
                case 'N':
                case 'n':
                    return -4;
                case 'D':
                case 'd':
                    return -4;
                case 'C':
                case 'c':
                    return -2;
                case 'Q':
                case 'q':
                    return -2;
                case 'E':
                case 'e':
                    return -3;
                case 'G':
                case 'g':
                    return -2;
                case 'H':
                case 'h':
                    return -2;
                case 'I':
                case 'i':
                    return -3;
                case 'L':
                case 'l':
                    return -2;
                case 'K':
                case 'k':
                    return -3;
                case 'M':
                case 'm':
                    return -1;
                case 'F':
                case 'f':
                    return 1;
                case 'P':
                case 'p':
                    return -4;
                case 'S':
                case 's':
                    return -3;
                case 'T':
                case 't':
                    return -2;
                case 'W':
                case 'w':
                    return 11;
                case 'Y':
                case 'y':
                    return 2;
                case 'V':
                case 'v':
                    return -3;
                case 'B':
                case 'b':
                    return -4;
                case 'Z':
                case 'z':
                    return -3;
                case 'X':
                case 'x':
                    return -2;
                default:
                    printf("Error in Scoring. Not found (%c,%c)", a, b);
                    return 0;
            }
            break;
        case 'Y':
        case 'y':
            switch (b) {
                case 'A':
                case 'a':
                    return -2;
                case 'R':
                case 'r':
                    return -2;
                case 'N':
                case 'n':
                    return -2;
                case 'D':
                case 'd':
                    return -3;
                case 'C':
                case 'c':
                    return -2;
                case 'Q':
                case 'q':
                    return -1;
                case 'E':
                case 'e':
                    return -2;
                case 'G':
                case 'g':
                    return -3;
                case 'H':
                case 'h':
                    return 2;
                case 'I':
                case 'i':
                    return -1;
                case 'L':
                case 'l':
                    return -1;
                case 'K':
                case 'k':
                    return -2;
                case 'M':
                case 'm':
                    return -1;
                case 'F':
                case 'f':
                    return 3;
                case 'P':
                case 'p':
                    return -3;
                case 'S':
                case 's':
                    return -2;
                case 'T':
                case 't':
                    return -2;
                case 'W':
                case 'w':
                    return 2;
                case 'Y':
                case 'y':
                    return 7;
                case 'V':
                case 'v':
                    return -1;
                case 'B':
                case 'b':
                    return -3;
                case 'Z':
                case 'z':
                    return -2;
                case 'X':
                case 'x':
                    return -1;
                default:
                    printf("Error in Scoring. Not found (%c,%c)", a, b);
                    return 0;
            }
            break;
        case 'V':
        case 'v':
            switch (b) {
                case 'A':
                case 'a':
                    return 0;
                case 'R':
                case 'r':
                    return -3;
                case 'N':
                case 'n':
                    return -3;
                case 'D':
                case 'd':
                    return -3;
                case 'C':
                case 'c':
                    return -1;
                case 'Q':
                case 'q':
                    return -2;
                case 'E':
                case 'e':
                    return -2;
                case 'G':
                case 'g':
                    return -3;
                case 'H':
                case 'h':
                    return -3;
                case 'I':
                case 'i':
                    return 3;
                case 'L':
                case 'l':
                    return 1;
                case 'K':
                case 'k':
                    return -2;
                case 'M':
                case 'm':
                    return 1;
                case 'F':
                case 'f':
                    return -1;
                case 'P':
                case 'p':
                    return -2;
                case 'S':
                case 's':
                    return -2;
                case 'T':
                case 't':
                    return 0;
                case 'W':
                case 'w':
                    return -3;
                case 'Y':
                case 'y':
                    return -1;
                case 'V':
                case 'v':
                    return 4;
                case 'B':
                case 'b':
                    return -3;
                case 'Z':
                case 'z':
                    return -2;
                case 'X':
                case 'x':
                    return -1;
                default:
                    printf("Error in Scoring. Not found (%c,%c)", a, b);
                    return 0;
            }
            break;
        case 'B':
        case 'b':
            switch (b) {
                case 'A':
                case 'a':
                    return -2;
                case 'R':
                case 'r':
                    return -1;
                case 'N':
                case 'n':
                    return 3;
                case 'D':
                case 'd':
                    return 4;
                case 'C':
                case 'c':
                    return -3;
                case 'Q':
                case 'q':
                    return 0;
                case 'E':
                case 'e':
                    return 1;
                case 'G':
                case 'g':
                    return -1;
                case 'H':
                case 'h':
                    return 0;
                case 'I':
                case 'i':
                    return -3;
                case 'L':
                case 'l':
                    return -4;
                case 'K':
                case 'k':
                    return 0;
                case 'M':
                case 'm':
                    return -3;
                case 'F':
                case 'f':
                    return -3;
                case 'P':
                case 'p':
                    return -2;
                case 'S':
                case 's':
                    return 0;
                case 'T':
                case 't':
                    return -1;
                case 'W':
                case 'w':
                    return -4;
                case 'Y':
                case 'y':
                    return -3;
                case 'V':
                case 'v':
                    return -3;
                case 'B':
                case 'b':
                    return 4;
                case 'Z':
                case 'z':
                    return 1;
                case 'X':
                case 'x':
                    return -1;
                default:
                    printf("Error in Scoring. Not found (%c,%c)", a, b);
                    return 0;
            }
            break;
        case 'Z':
        case 'z':
            switch (b) {
                case 'A':
                case 'a':
                    return -1;
                case 'R':
                case 'r':
                    return 0;
                case 'N':
                case 'n':
                    return 0;
                case 'D':
                case 'd':
                    return 1;
                case 'C':
                case 'c':
                    return -3;
                case 'Q':
                case 'q':
                    return 3;
                case 'E':
                case 'e':
                    return 4;
                case 'G':
                case 'g':
                    return -2;
                case 'H':
                case 'h':
                    return 0;
                case 'I':
                case 'i':
                    return -3;
                case 'L':
                case 'l':
                    return -3;
                case 'K':
                case 'k':
                    return 1;
                case 'M':
                case 'm':
                    return -1;
                case 'F':
                case 'f':
                    return -3;
                case 'P':
                case 'p':
                    return -1;
                case 'S':
                case 's':
                    return 0;
                case 'T':
                case 't':
                    return -1;
                case 'W':
                case 'w':
                    return -3;
                case 'Y':
                case 'y':
                    return -2;
                case 'V':
                case 'v':
                    return -2;
                case 'B':
                case 'b':
                    return 1;
                case 'Z':
                case 'z':
                    return 4;
                case 'X':
                case 'x':
                    return -1;
                default:
                    printf("Error in Scoring. Not found (%c,%c)", a, b);
                    return 0;
            }
            break;
        case 'X':
        case 'x':
            switch (b) {
                case 'A':
                case 'a':
                    return 0;
                case 'R':
                case 'r':
                    return -1;
                case 'N':
                case 'n':
                    return -1;
                case 'D':
                case 'd':
                    return -1;
                case 'C':
                case 'c':
                    return -2;
                case 'Q':
                case 'q':
                    return -1;
                case 'E':
                case 'e':
                    return -1;
                case 'G':
                case 'g':
                    return -1;
                case 'H':
                case 'h':
                    return -1;
                case 'I':
                case 'i':
                    return -1;
                case 'L':
                case 'l':
                    return -1;
                case 'K':
                case 'k':
                    return -1;
                case 'M':
                case 'm':
                    return -1;
                case 'F':
                case 'f':
                    return -1;
                case 'P':
                case 'p':
                    return -2;
                case 'S':
                case 's':
                    return 0;
                case 'T':
                case 't':
                    return 0;
                case 'W':
                case 'w':
                    return -2;
                case 'Y':
                case 'y':
                    return -1;
                case 'V':
                case 'v':
                    return -1;
                case 'B':
                case 'b':
                    return -1;
                case 'Z':
                case 'z':
                    return -1;
                case 'X':
                case 'x':
                    return -1;
                default:
                    printf("Error in Scoring. Not found (%c,%c)", a, b);
                    return 0;
            }
            break;
        default:
            printf("Error in Scoring. Not found (%c,%c)", a, b);
            return 0;
    }
}